name: Upload Release Assets

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  BEVY_ASSET_PATH: "/project/kodecks-bevy/assets"

jobs:
  release-linux:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.3
      - name: Install cross
        run: cargo binstall cross --force -y
      - name: Build project
        run: cross build -p kodecks-bevy --profile distribution --features embed_assets --target ${{ matrix.toolchain }}
      - name: Make archive
        run: tar -C target/${{ matrix.toolchain }}/distribution -Jcvf kodecks-${{ matrix.toolchain }}.tar.xz kodecks

  release-macos:
    name: Upload Release Assets (macOS)
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain: [aarch64-apple-darwin, aarch64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker on macOS
        run: brew install docker
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.3
      - name: Install cross
        run: cargo binstall cross --force -y
      - name: Build project
        run: cross build -p kodecks-bevy --profile distribution --features embed_assets --target ${{ matrix.toolchain }}
      - name: Make archive
        run: tar -C target/${{ matrix.toolchain }}/distribution -Jcvf kodecks-${{ matrix.toolchain }}.tar.xz kodecks
