name: Upload Release Assets

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  BEVY_ASSET_PATH: "/project/kodecks/kodecks-bevy/assets"

jobs:
  release-linux:
    strategy:
      matrix:
        toolchain: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.3
      - name: Install cross
        run: cargo binstall cross --force -y
      - name: Build project
        run: cross build -p kodecks-bevy --profile distribution --features embed_assets --target ${{ matrix.toolchain }}
      - name: Make archive
        run: tar -C target/${{ matrix.toolchain }}/release -Jcvf kodecks-${{ matrix.toolchain }}.tar.xz kodecks
